import { type Lang } from '@/lib/i18n'

const content = {
  en: {
    title: 'Terms of use',
    updated: 'Last updated: March 2026',
    sections: [
      { h: 'Acceptance', p: 'By accessing Rekapp, you agree to these terms. If you do not agree, please do not use the platform.' },
      { h: 'Service description', p: 'Rekapp is an AI-powered financial news platform that generates articles about stock price movements. Content is produced by artificial intelligence models and is intended for informational purposes only.' },
      { h: 'Not financial advice', p: 'Nothing on Rekapp constitutes financial, investment, tax, or legal advice. AI-generated content may contain errors or inaccuracies. Always consult a qualified financial advisor before making investment decisions. Rekapp is not responsible for any financial losses incurred as a result of using information on this platform.' },
      { h: 'AI-generated content', p: 'All articles are generated by AI models (including Google Gemini and Anthropic Claude) and fact-checked automatically. While we strive for accuracy, AI-generated content may occasionally contain factual errors, outdated information, or misinterpretations.' },
      { h: 'Intellectual property', p: 'All content, design, and code on Rekapp is owned by Rekapp. You may share articles with attribution but may not republish or scrape content without permission.' },
      { h: 'Availability', p: 'Rekapp is provided "as is" without warranty. We do not guarantee uninterrupted access or error-free content. We may modify, suspend, or discontinue the service at any time.' },
      { h: 'Limitation of liability', p: 'To the maximum extent permitted by law, Rekapp and its operators shall not be liable for any direct, indirect, incidental, or consequential damages arising from your use of the platform.' },
      { h: 'Changes', p: 'We may update these terms at any time. Continued use of the platform constitutes acceptance of the updated terms.' },
    ],
  },
  it: {
    title: 'Termini di utilizzo',
    updated: 'Ultimo aggiornamento: marzo 2026',
    sections: [
      { h: 'Accettazione', p: 'Accedendo a Rekapp, accetti questi termini. Se non sei d\'accordo, ti preghiamo di non utilizzare la piattaforma.' },
      { h: 'Descrizione del servizio', p: "Rekapp \u00e8 una piattaforma di notizie finanziarie basata sull'intelligenza artificiale che genera articoli sui movimenti dei prezzi azionari. I contenuti sono prodotti da modelli di IA e sono destinati esclusivamente a scopi informativi." },
      { h: 'Non costituisce consulenza finanziaria', p: 'Nulla su Rekapp costituisce consulenza finanziaria, di investimento, fiscale o legale. I contenuti generati dall\'IA possono contenere errori. Consulta sempre un consulente finanziario qualificato prima di prendere decisioni di investimento.' },
      { h: 'Contenuti generati dall\'IA', p: 'Tutti gli articoli sono generati da modelli di IA (tra cui Google Gemini e Anthropic Claude) e verificati automaticamente. Nonostante i nostri sforzi per garantire l\'accuratezza, i contenuti possono occasionalmente contenere errori.' },
      { h: 'Propriet\u00e0 intellettuale', p: 'Tutti i contenuti, il design e il codice su Rekapp sono di propriet\u00e0 di Rekapp. \u00c8 possibile condividere gli articoli con attribuzione, ma non \u00e8 consentito ripubblicare o estrarre contenuti senza autorizzazione.' },
      { h: 'Disponibilit\u00e0', p: 'Rekapp \u00e8 fornito "cos\u00ec com\'\u00e8" senza garanzie. Non garantiamo un accesso ininterrotto o contenuti privi di errori.' },
      { h: 'Limitazione di responsabilit\u00e0', p: 'Nella misura massima consentita dalla legge, Rekapp e i suoi operatori non saranno responsabili per danni diretti, indiretti, incidentali o consequenziali derivanti dall\'utilizzo della piattaforma.' },
      { h: 'Modifiche', p: 'Potremmo aggiornare questi termini in qualsiasi momento. L\'uso continuato della piattaforma costituisce accettazione dei termini aggiornati.' },
    ],
  },
  fr: {
    title: "Conditions d'utilisation",
    updated: 'Derni\u00e8re mise \u00e0 jour : mars 2026',
    sections: [
      { h: 'Acceptation', p: "En acc\u00e9dant \u00e0 Rekapp, vous acceptez ces conditions. Si vous n'\u00eates pas d'accord, veuillez ne pas utiliser la plateforme." },
      { h: 'Description du service', p: "Rekapp est une plateforme d'actualit\u00e9s financi\u00e8res aliment\u00e9e par l'IA qui g\u00e9n\u00e8re des articles sur les mouvements boursiers. Le contenu est produit par des mod\u00e8les d'IA et est destin\u00e9 \u00e0 des fins informatives uniquement." },
      { h: 'Pas un conseil financier', p: "Rien sur Rekapp ne constitue un conseil financier, d'investissement, fiscal ou juridique. Consultez toujours un conseiller financier qualifi\u00e9." },
      { h: 'Contenu g\u00e9n\u00e9r\u00e9 par l\'IA', p: "Tous les articles sont g\u00e9n\u00e9r\u00e9s par des mod\u00e8les d'IA et v\u00e9rifi\u00e9s automatiquement. Le contenu peut occasionnellement contenir des erreurs." },
      { h: 'Propri\u00e9t\u00e9 intellectuelle', p: "Tout le contenu de Rekapp est la propri\u00e9t\u00e9 de Rekapp. Le partage avec attribution est autoris\u00e9." },
      { h: 'Disponibilit\u00e9', p: 'Rekapp est fourni "tel quel" sans garantie.' },
      { h: 'Limitation de responsabilit\u00e9', p: "Rekapp ne sera pas responsable des dommages directs ou indirects r\u00e9sultant de l'utilisation de la plateforme." },
      { h: 'Modifications', p: "Nous pouvons mettre \u00e0 jour ces conditions. L'utilisation continue constitue une acceptation." },
    ],
  },
}

export default async function TermsPage({ params }: { params: Promise<{ lang: string }> }) {
  const { lang } = await params
  const c = content[lang as keyof typeof content] ?? content.en
  return (
    <div className="page" style={{ maxWidth: 700, paddingTop: 32, paddingBottom: 64 }}>
      <h1 className="page-title" style={{ marginBottom: 8 }}>{c.title}</h1>
      <p style={{ fontFamily: "'DM Mono', monospace", fontSize: '0.54rem', letterSpacing: '0.1em', color: 'var(--text-dim)', marginBottom: 32 }}>{c.updated}</p>
      {c.sections.map((s, i) => (
        <div key={i} style={{ marginBottom: 24 }}>
          <h2 style={{ fontFamily: "'Playfair Display', serif", fontSize: '1.1rem', color: 'var(--text)', marginBottom: 8 }}>{s.h}</h2>
          <p style={{ fontSize: '0.85rem', lineHeight: 1.7, color: 'var(--text-dim)' }}>{s.p}</p>
        </div>
      ))}
    </div>
  )
}
