#!/usr/bin/env python3
"""
Rekapp Web — Full scaffold script.
Run from Cloud Shell: python3 ~/scaffold.py
"""

import os

BASE = os.path.expanduser("~/rekapp-web")

files = {}

# ─── src/lib/supabase.ts ────────────────────────────────────────────────────
files["src/lib/supabase.ts"] = """\
import { createClient } from '@supabase/supabase-js'

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!

export const supabase = createClient(supabaseUrl, supabaseAnonKey)
"""

# ─── src/lib/types.ts ───────────────────────────────────────────────────────
files["src/lib/types.ts"] = """\
export type Article = {
  id: string
  stock_id: string
  alert_id: string
  country_code: string
  lang_code: string
  headline: string
  body: string
  explainer_body: string
  meta_title: string
  meta_description: string
  meta_slug: string
  tags: string | string[]
  published: boolean
  published_at: string
  created_at: string
  stocks?: Stock
  alerts?: Alert
}

export type Stock = {
  id: string
  symbol: string
  name: string
  sector: string
  sub_industry: string
  cap_tier: 'large' | 'mid' | 'small'
  country_code: string
}

export type Alert = {
  id: string
  stock_id: string
  direction: 'up' | 'down'
  change_pct: number
  price_at_alert: number
  previous_close: number
  triggered_at: string
}

export type Language = 'en' | 'it'

export type Country = {
  code: string
  name: string
  flag: string
  index: string
  active: boolean
}

export function parseTags(tags: string | string[] | null | undefined): string[] {
  if (!tags) return []
  if (Array.isArray(tags)) return tags
  try {
    const parsed = JSON.parse(tags)
    return Array.isArray(parsed) ? parsed : []
  } catch {
    return []
  }
}
"""

# ─── src/lib/i18n.ts ────────────────────────────────────────────────────────
files["src/lib/i18n.ts"] = """\
export const languages = ['en', 'it'] as const
export type Lang = typeof languages[number]

export const ui = {
  en: {
    nav: {
      feed: 'Live Feed',
      markets: 'Markets',
      topics: 'Topics',
      archive: 'Archive',
      search: 'Search',
    },
    feed: {
      eyebrow: 'Markets active globally',
      title: 'Live feed',
      titleEm: 'as it happens',
      readMore: 'Read story \u2192',
      filter: {
        all: 'All markets',
        gainers: 'Gainers',
        losers: 'Losers',
        big: 'Big moves',
      },
    },
    sidebar: {
      indices: 'Indices',
      movers: 'Top movers',
      search: 'Search',
      topics: 'Topics',
      allMarkets: 'All markets \u2192',
    },
    markets: {
      title: 'Markets',
      sub: 'Financial intelligence across global indices. Click a market to see its latest stories.',
      active: 'Active',
      soon: 'Coming soon',
      status: { open: 'Open', closed: 'Closed', soon: 'Soon' },
      stat: { today: 'Today', moves: 'Moves', stories: 'Stories' },
      latest: 'Latest stories',
    },
    topics: {
      title: 'Topics',
      earnings: 'Earnings',
      analysts: 'Analysts',
      ai: 'AI',
      banks: 'Banks',
      energy: 'Energy',
      evs: 'Electric Vehicles',
      semiconductors: 'Semiconductors',
      macro: 'Macro',
      ma: 'M&A',
      rates: 'Interest Rates',
      ipo: 'IPO',
      fda: 'FDA',
      trade: 'Trade / Tariffs',
    },
    archive: {
      title: 'Archive',
      sub: 'Every story, every market, every day.',
      filter: {
        market: 'Market',
        direction: 'Direction',
        topic: 'Topic',
        all: 'All',
        gainers: 'Gainers',
        losers: 'Losers',
        done: 'Done',
      },
      filters: 'Filters',
      stories: 'Stories',
      noResults: 'No stories match the selected filters.',
    },
    article: {
      byline: 'Generated by Rekapp',
      factChecked: '\u2713 Fact-checked',
      whatItMeans: 'What does it mean',
      tags: 'Tags',
      related: 'Related stories',
      back: '\u2190 Back',
      moveThreshold: 'Move threshold',
      previousClose: 'Previous close',
      dayHigh: 'Day high',
      dayLow: 'Day low',
      capTier: 'Cap tier',
      large: 'Large',
      mid: 'Mid',
      small: 'Small',
    },
    search: {
      title: 'Search',
      placeholder: 'Ticker or keyword...',
      hint: 'Try: NVDA \u00b7 UCG.MI \u00b7 earnings \u00b7 export controls',
      go: 'Go',
    },
    footer: {
      copy: 'Automated financial intelligence',
    },
  },
  it: {
    nav: {
      feed: 'Notizie in tempo reale',
      markets: 'Mercati',
      topics: 'Argomenti',
      archive: 'Archivio',
      search: 'Cerca',
    },
    feed: {
      eyebrow: 'Mercati attivi globalmente',
      title: 'Notizie in tempo reale',
      titleEm: 'mentre accadono',
      readMore: "Leggi l'articolo \u2192",
      filter: {
        all: 'Tutti i mercati',
        gainers: 'Rialzi',
        losers: 'Ribassi',
        big: 'Movimenti forti',
      },
    },
    sidebar: {
      indices: 'Indici',
      movers: 'Maggiori movimenti',
      search: 'Cerca',
      topics: 'Argomenti',
      allMarkets: 'Tutti i mercati \u2192',
    },
    markets: {
      title: 'Mercati',
      sub: 'Intelligenza finanziaria sui principali indici globali. Clicca su un mercato per vedere le ultime notizie.',
      active: 'Attivi',
      soon: 'Prossimamente',
      status: { open: 'Aperto', closed: 'Chiuso', soon: 'Presto' },
      stat: { today: 'Oggi', moves: 'Movimenti', stories: 'Articoli' },
      latest: 'Ultime notizie',
    },
    topics: {
      title: 'Argomenti',
      earnings: 'Risultati finanziari',
      analysts: 'Analisti',
      ai: 'IA',
      banks: 'Banche',
      energy: 'Energia',
      evs: 'Veicoli elettrici',
      semiconductors: 'Semiconduttori',
      macro: 'Macro',
      ma: 'Fusioni e acquisizioni',
      rates: "Tassi d'interesse",
      ipo: 'IPO',
      fda: 'FDA',
      trade: 'Commercio / Dazi',
    },
    archive: {
      title: 'Archivio',
      sub: 'Ogni articolo, ogni mercato, ogni giorno.',
      filter: {
        market: 'Mercato',
        direction: 'Direzione',
        topic: 'Argomento',
        all: 'Tutti',
        gainers: 'Rialzi',
        losers: 'Ribassi',
        done: 'Fatto',
      },
      filters: 'Filtri',
      stories: 'Articoli',
      noResults: 'Nessun articolo corrisponde ai filtri selezionati.',
    },
    article: {
      byline: 'Generato da Rekapp',
      factChecked: '\u2713 Verificato',
      whatItMeans: 'Cosa significa',
      tags: 'Tag',
      related: 'Articoli correlati',
      back: '\u2190 Indietro',
      moveThreshold: 'Soglia di movimento',
      previousClose: 'Chiusura precedente',
      dayHigh: 'Massimo giornaliero',
      dayLow: 'Minimo giornaliero',
      capTier: 'Capitalizzazione',
      large: 'Grande',
      mid: 'Media',
      small: 'Piccola',
    },
    search: {
      title: 'Cerca',
      placeholder: 'Ticker o parola chiave...',
      hint: 'Prova: NVDA \u00b7 UCG.MI \u00b7 risultati \u00b7 controlli export',
      go: 'Vai',
    },
    footer: {
      copy: 'Intelligenza finanziaria automatizzata',
    },
  },
} as const

export function useTranslations(lang: Lang) {
  return ui[lang]
}
"""

# ─── src/lib/countries.ts ───────────────────────────────────────────────────
files["src/lib/countries.ts"] = """\
export type CountryConfig = {
  code: string
  name: string
  flag: string
  index: string
  currency: string
  active: boolean
}

export const COUNTRIES: CountryConfig[] = [
  { code: 'us', name: 'United States', flag: '\U0001f1fa\U0001f1f8', index: 'S&P 500',    currency: 'USD', active: true  },
  { code: 'it', name: 'Italy',         flag: '\U0001f1ee\U0001f1f9', index: 'FTSE MIB',   currency: 'EUR', active: true  },
  { code: 'gb', name: 'United Kingdom',flag: '\U0001f1ec\U0001f1e7', index: 'FTSE 100',   currency: 'GBP', active: false },
  { code: 'de', name: 'Germany',       flag: '\U0001f1e9\U0001f1ea', index: 'DAX 40',     currency: 'EUR', active: false },
  { code: 'es', name: 'Spain',         flag: '\U0001f1ea\U0001f1f8', index: 'IBEX 35',    currency: 'EUR', active: false },
  { code: 'br', name: 'Brazil',        flag: '\U0001f1e7\U0001f1f7', index: 'Bovespa',    currency: 'BRL', active: false },
  { code: 'fr', name: 'France',        flag: '\U0001f1eb\U0001f1f7', index: 'CAC 40',     currency: 'EUR', active: false },
  { code: 'jp', name: 'Japan',         flag: '\U0001f1ef\U0001f1f5', index: 'Nikkei 225', currency: 'JPY', active: false },
]

export const ACTIVE_COUNTRIES = COUNTRIES.filter(c => c.active)

export function getCountry(code: string): CountryConfig | undefined {
  return COUNTRIES.find(c => c.code === code)
}
"""

# ─── src/app/globals.css ────────────────────────────────────────────────────
files["src/app/globals.css"] = """\
@import "tailwindcss";

:root {
  --ink:         #0d0c0b;
  --ink-raised:  #161513;
  --ink-card:    #131210;
  --ink-border:  #242220;
  --ink-hover:   #1c1b19;
  --text:        #c8c1b5;
  --text-dim:    #635e58;
  --gold:        #c4a25e;
  --gold-border: #3a3020;
  --up:          #5d9e70;
  --down:        #b05a5a;
  --pad:         40px;
}

@media (max-width: 640px)  { :root { --pad: 16px; } }
@media (min-width: 641px) and (max-width: 1024px) { :root { --pad: 24px; } }

html, body {
  background: var(--ink);
  color: var(--text);
  min-height: 100vh;
}

body::after {
  content: '';
  position: fixed;
  inset: 0;
  background-image: url("data:image/svg+xml,%3Csvg viewBox='0 0 200 200' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.85' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='0.022'/%3E%3C/svg%3E");
  pointer-events: none;
  z-index: 9999;
}

@theme {
  --color-ink:         #0d0c0b;
  --color-ink-raised:  #161513;
  --color-ink-card:    #131210;
  --color-ink-border:  #242220;
  --color-ink-hover:   #1c1b19;
  --color-text:        #c8c1b5;
  --color-text-dim:    #635e58;
  --color-gold:        #c4a25e;
  --color-gold-border: #3a3020;
  --color-up:          #5d9e70;
  --color-down:        #b05a5a;
  --font-playfair: 'Playfair Display', serif;
  --font-dm-sans:  'DM Sans', sans-serif;
  --font-dm-mono:  'DM Mono', monospace;
}
"""

# ─── src/app/layout.tsx (root) ──────────────────────────────────────────────
files["src/app/layout.tsx"] = """\
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return children
}
"""

# ─── src/app/page.tsx (root redirect) ───────────────────────────────────────
files["src/app/page.tsx"] = """\
import { redirect } from 'next/navigation'

export default function RootPage() {
  redirect('/en')
}
"""

# ─── src/app/[lang]/layout.tsx ──────────────────────────────────────────────
files["src/app/[lang]/layout.tsx"] = """\
import type { Metadata } from 'next'
import { Playfair_Display, DM_Sans, DM_Mono } from 'next/font/google'
import { languages } from '@/lib/i18n'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import type { Lang } from '@/lib/i18n'
import '../globals.css'

const playfair = Playfair_Display({
  subsets: ['latin'],
  variable: '--font-playfair',
  display: 'swap',
})

const dmSans = DM_Sans({
  subsets: ['latin'],
  variable: '--font-dm-sans',
  display: 'swap',
})

const dmMono = DM_Mono({
  subsets: ['latin'],
  variable: '--font-dm-mono',
  weight: ['400', '500'],
  display: 'swap',
})

export async function generateStaticParams() {
  return languages.map(lang => ({ lang }))
}

export const metadata: Metadata = {
  title: 'Rekapp \u2014 Financial Intelligence',
  description: 'AI-generated financial intelligence for global markets.',
}

export default async function LangLayout({
  children,
  params,
}: {
  children: React.ReactNode
  params: Promise<{ lang: string }>
}) {
  const { lang } = await params
  return (
    <html
      lang={lang}
      className={`${playfair.variable} ${dmSans.variable} ${dmMono.variable}`}
    >
      <body className="bg-[--ink] text-[--text] antialiased font-[family-name:var(--font-dm-sans)]">
        <Header lang={lang as Lang} />
        <main>{children}</main>
        <Footer lang={lang as Lang} />
      </body>
    </html>
  )
}
"""

# ─── src/app/[lang]/page.tsx ────────────────────────────────────────────────
files["src/app/[lang]/page.tsx"] = """\
import { supabase } from '@/lib/supabase'
import { useTranslations, type Lang } from '@/lib/i18n'
import { type Article } from '@/lib/types'
import FeedItem from '@/components/FeedItem'
import Sidebar from '@/components/Sidebar'
import Ticker from '@/components/Ticker'

export const revalidate = 60

async function getArticles(lang: string): Promise<Article[]> {
  const { data, error } = await supabase
    .from('articles')
    .select('*, stocks(symbol, name, sector, cap_tier, country_code), alerts(direction, change_pct, price_at_alert, previous_close, triggered_at)')
    .eq('lang_code', lang)
    .eq('published', true)
    .order('published_at', { ascending: false })
    .limit(50)
  if (error) { console.error('Feed fetch error:', error); return [] }
  return data ?? []
}

async function getTickerData() {
  const { data } = await supabase
    .from('articles')
    .select('stocks(symbol), alerts(direction, change_pct)')
    .eq('published', true)
    .order('published_at', { ascending: false })
    .limit(20)
  return data ?? []
}

export default async function HomePage({
  params,
}: {
  params: Promise<{ lang: string }>
}) {
  const { lang } = await params
  const t = useTranslations(lang as Lang)
  const [articles, tickerRaw] = await Promise.all([getArticles(lang), getTickerData()])

  const tickerItems = tickerRaw
    .filter((r: any) => r.stocks?.symbol && r.alerts?.change_pct != null)
    .map((r: any) => ({ symbol: r.stocks.symbol, change_pct: r.alerts.change_pct }))

  const grouped = articles.reduce((acc: Record<string, Article[]>, article) => {
    const date = new Date(article.published_at).toLocaleDateString(
      lang === 'it' ? 'it-IT' : 'en-GB',
      { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' }
    )
    if (!acc[date]) acc[date] = []
    acc[date].push(article)
    return acc
  }, {})

  const today = new Date().toLocaleDateString(
    lang === 'it' ? 'it-IT' : 'en-GB',
    { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' }
  )

  return (
    <>
      <Ticker items={tickerItems} />
      <div className="max-w-[1240px] mx-auto px-[--pad]">
        <div className="py-8 border-b border-[--ink-border]">
          <div className="font-[family-name:var(--font-dm-mono)] text-[0.54rem] tracking-[0.18em] uppercase text-[--gold] mb-2">
            {t.feed.eyebrow}
          </div>
          <h1 className="font-[family-name:var(--font-playfair)] text-[clamp(1.7rem,3vw,2.8rem)] font-normal tracking-tight text-[--text] leading-[1.15]">
            {t.feed.title} \u2014 <em className="italic text-[--gold]">{t.feed.titleEm}</em>
          </h1>
        </div>

        <div className="flex gap-0">
          <div className="flex-1 border-r border-[--ink-border] min-w-0">
            {Object.entries(grouped).map(([date, dayArticles], groupIndex) => (
              <div key={date}>
                <div className="sticky top-[52px] z-10 flex items-center gap-3 px-5 py-3.5 bg-[--ink-raised] border-b border-[--ink-border]">
                  <span className="font-[family-name:var(--font-dm-mono)] text-[0.56rem] tracking-[0.14em] uppercase text-[--gold] whitespace-nowrap">
                    {date === today ? (lang === 'it' ? 'Oggi' : 'Today') + ' \u2014 ' + date : date}
                  </span>
                  <div className="flex-1 h-px bg-[--ink-border]" />
                  <span className="font-[family-name:var(--font-dm-mono)] text-[0.54rem] tracking-[0.1em] text-[--text-dim] whitespace-nowrap">
                    {dayArticles.length} {t.archive.stories.toLowerCase()}
                  </span>
                </div>
                {dayArticles.map((article, i) => (
                  <FeedItem key={article.id} article={article} lang={lang as Lang} hero={groupIndex === 0 && i === 0} />
                ))}
              </div>
            ))}
            {articles.length === 0 && (
              <div className="p-10 font-[family-name:var(--font-dm-mono)] text-[0.62rem] tracking-[0.1em] text-[--text-dim]">
                {lang === 'it' ? 'Nessun articolo disponibile.' : 'No articles available yet.'}
              </div>
            )}
          </div>
          <Sidebar lang={lang as Lang} />
        </div>
      </div>
    </>
  )
}
"""

# ─── src/components/Ticker.tsx ──────────────────────────────────────────────
files["src/components/Ticker.tsx"] = """\
type TickerItem = {
  symbol: string
  change_pct: number
}

export default function Ticker({ items }: { items: TickerItem[] }) {
  if (!items.length) return null
  const display = [...items, ...items]
  return (
    <div className="h-[30px] bg-[--ink-raised] border-b border-[--ink-border] flex items-center overflow-hidden">
      <div className="shrink-0 px-3.5 h-full flex items-center border-r border-[--ink-border] font-[family-name:var(--font-dm-mono)] text-[0.54rem] tracking-[0.16em] uppercase text-[--gold]">
        Live
      </div>
      <div className="overflow-hidden flex-1">
        <div className="flex gap-10 whitespace-nowrap pl-10" style={{ animation: 'ticker 55s linear infinite' }}>
          {display.map((item, i) => {
            const up = item.change_pct >= 0
            return (
              <span key={i} className="flex items-center gap-2 font-[family-name:var(--font-dm-mono)] text-[0.6rem]">
                <span className="text-[--text] font-medium">{item.symbol}</span>
                <span className={up ? 'text-[--up]' : 'text-[--down]'}>
                  {up ? '\u25b4' : '\u25be'} {up ? '+' : ''}{item.change_pct.toFixed(1)}%
                </span>
              </span>
            )
          })}
        </div>
      </div>
      <style>{`@keyframes ticker { from{transform:translateX(0)} to{transform:translateX(-50%)} }`}</style>
    </div>
  )
}
"""

# ─── src/components/Header.tsx ──────────────────────────────────────────────
files["src/components/Header.tsx"] = """\
'use client'

import Link from 'next/link'
import { usePathname } from 'next/navigation'
import { useState } from 'react'
import { type Lang, useTranslations } from '@/lib/i18n'

export default function Header({ lang }: { lang: Lang }) {
  const t = useTranslations(lang)
  const pathname = usePathname()
  const [mobOpen, setMobOpen] = useState(false)
  const [langOpen, setLangOpen] = useState(false)

  const otherLang = lang === 'en' ? 'it' : 'en'
  const otherLangLabel = lang === 'en' ? '\U0001f1ee\U0001f1f9 IT' : '\U0001f1ec\U0001f1e7 EN'
  const currentFlag = lang === 'en' ? '\U0001f1ec\U0001f1e7' : '\U0001f1ee\U0001f1f9'
  const switchLangPath = pathname.replace(`/${lang}`, `/${otherLang}`)

  const navItems = [
    { href: `/${lang}`,         label: t.nav.feed },
    { href: `/${lang}/markets`, label: t.nav.markets },
    { href: `/${lang}/topics`,  label: t.nav.topics },
    { href: `/${lang}/archive`, label: t.nav.archive },
    { href: `/${lang}/search`,  label: t.nav.search },
  ]

  const isActive = (href: string) =>
    href === `/${lang}` ? pathname === `/${lang}` : pathname.startsWith(href)

  return (
    <>
      <header className="sticky top-0 z-50 h-[52px] flex items-center px-[--pad] gap-4 border-b border-[--ink-border] bg-[rgba(13,12,11,0.96)] backdrop-blur-md">
        <button
          className="md:hidden flex flex-col justify-center gap-[5px] w-8 h-8 p-1 shrink-0"
          onClick={() => setMobOpen(o => !o)}
          aria-label="Menu"
        >
          <span className={`block h-px bg-[--text-dim] transition-all duration-200 ${mobOpen ? 'w-[18px] rotate-45 translate-y-[6px]' : 'w-[20px]'}`} />
          <span className={`block h-px bg-[--text-dim] transition-all duration-200 ${mobOpen ? 'w-[18px] -rotate-45' : 'w-[14px]'}`} />
        </button>

        <Link
          href={`/${lang}`}
          className="font-[family-name:var(--font-playfair)] text-[1.3rem] font-semibold tracking-tight text-[--text] shrink-0 absolute left-1/2 -translate-x-1/2 md:static md:translate-x-0"
        >
          Rek<span className="text-[--gold]">app</span>
        </Link>

        <nav className="hidden md:flex items-stretch h-full ml-8">
          {navItems.map(item => (
            <Link
              key={item.href}
              href={item.href}
              className={`flex items-center px-4 h-full font-[family-name:var(--font-dm-mono)] text-[0.6rem] tracking-[0.1em] uppercase border-b-2 transition-colors whitespace-nowrap
                ${isActive(item.href) ? 'text-[--text] border-[--gold]' : 'text-[--text-dim] border-transparent hover:text-[--text]'}`}
            >
              {item.label}
            </Link>
          ))}
        </nav>

        <div className="flex items-center gap-3 ml-auto">
          <div className="relative">
            <button
              onClick={() => setLangOpen(o => !o)}
              className={`flex items-center gap-1.5 px-[10px] py-[5px] border font-[family-name:var(--font-dm-mono)] text-[0.6rem] tracking-[0.1em] transition-all
                ${langOpen ? 'text-[--gold] border-[--gold-border]' : 'text-[--text-dim] border-[--ink-border] hover:text-[--gold] hover:border-[--gold-border]'}`}
            >
              <span>{currentFlag}</span>
              <span>{lang.toUpperCase()}</span>
              <span className={`text-[0.45rem] opacity-50 transition-transform ${langOpen ? 'rotate-180' : ''}`}>\u25bc</span>
            </button>
            {langOpen && (
              <div className="absolute top-[calc(100%+6px)] right-0 min-w-[140px] bg-[--ink-raised] border border-[--ink-border] z-[600]">
                <Link
                  href={switchLangPath}
                  onClick={() => setLangOpen(false)}
                  className="flex items-center gap-2.5 px-3.5 py-2.5 font-[family-name:var(--font-dm-mono)] text-[0.62rem] text-[--text-dim] hover:bg-[--ink-hover] hover:text-[--text] transition-colors"
                >
                  {otherLangLabel}
                </Link>
              </div>
            )}
          </div>
          <div className="hidden sm:flex items-center gap-1.5 px-[9px] py-1 border border-[--gold-border] font-[family-name:var(--font-dm-mono)] text-[0.58rem] tracking-[0.1em] text-[--gold]">
            <span className="w-[5px] h-[5px] rounded-full bg-[--gold] animate-pulse" />
            Live
          </div>
        </div>
      </header>

      {mobOpen && (
        <div className="fixed top-[52px] left-0 right-0 bottom-0 bg-[--ink-raised] z-40 overflow-y-auto md:hidden">
          <div className="border-b border-[--ink-border]">
            {navItems.map(item => (
              <Link
                key={item.href}
                href={item.href}
                onClick={() => setMobOpen(false)}
                className={`flex items-center px-[--pad] py-3.5 font-[family-name:var(--font-dm-mono)] text-[0.65rem] tracking-[0.1em] uppercase border-t border-[--ink-border] transition-colors
                  ${isActive(item.href) ? 'text-[--gold]' : 'text-[--text-dim] hover:text-[--text]'}`}
              >
                {item.label}
              </Link>
            ))}
          </div>
          <div className="px-[--pad] py-4">
            <div className="font-[family-name:var(--font-dm-mono)] text-[0.52rem] tracking-[0.16em] uppercase text-[--gold] mb-3">
              Language / Lingua
            </div>
            <Link
              href={switchLangPath}
              onClick={() => setMobOpen(false)}
              className="inline-flex items-center gap-1.5 px-3.5 py-1.5 border border-[--ink-border] font-[family-name:var(--font-dm-mono)] text-[0.6rem] text-[--text-dim] hover:text-[--gold] hover:border-[--gold-border] transition-all"
            >
              {otherLangLabel}
            </Link>
          </div>
        </div>
      )}
    </>
  )
}
"""

# ─── src/components/Footer.tsx ──────────────────────────────────────────────
files["src/components/Footer.tsx"] = """\
import Link from 'next/link'
import { type Lang, useTranslations } from '@/lib/i18n'

export default function Footer({ lang }: { lang: Lang }) {
  const t = useTranslations(lang)
  return (
    <footer className="border-t border-[--ink-border] px-[--pad] py-6 flex justify-between items-center flex-wrap gap-3 mt-16">
      <Link href={`/${lang}`} className="font-[family-name:var(--font-playfair)] text-[0.95rem] text-[--text-dim]">
        Rek<span className="text-[--gold]">app</span>
      </Link>
      <span className="font-[family-name:var(--font-dm-mono)] text-[0.52rem] tracking-[0.08em] text-[--text-dim]">
        \u00a9 {new Date().getFullYear()} Rekapp \u00b7 {t.footer.copy}
      </span>
    </footer>
  )
}
"""

# ─── src/components/FeedItem.tsx ────────────────────────────────────────────
files["src/components/FeedItem.tsx"] = """\
import Link from 'next/link'
import { type Article, parseTags } from '@/lib/types'
import { type Lang, useTranslations } from '@/lib/i18n'

export default function FeedItem({
  article,
  lang,
  hero = false,
}: {
  article: Article
  lang: Lang
  hero?: boolean
}) {
  const t = useTranslations(lang)
  const stock = (article as any).stocks
  const alert = (article as any).alerts
  const tags = parseTags(article.tags).slice(0, 2)
  const up = alert?.direction === 'up'
  const time = new Date(article.published_at).toLocaleTimeString(
    lang === 'it' ? 'it-IT' : 'en-GB',
    { hour: '2-digit', minute: '2-digit' }
  )

  const Meta = () => (
    <div className="flex items-center gap-2 mb-2.5 flex-wrap">
      {stock?.symbol && (
        <span className="font-[family-name:var(--font-dm-mono)] text-[0.6rem] font-medium text-[--text] bg-[--ink-border] px-[7px] py-[2px]">
          {stock.symbol}
        </span>
      )}
      {alert?.change_pct != null && (
        <span className={`font-[family-name:var(--font-dm-mono)] text-[0.6rem] font-medium ${up ? 'text-[--up]' : 'text-[--down]'}`}>
          {up ? '\u25b4' : '\u25be'} {up ? '+' : ''}{Number(alert.change_pct).toFixed(1)}%
        </span>
      )}
      {article.country_code && (
        <span className="font-[family-name:var(--font-dm-mono)] text-[0.5rem] tracking-[0.12em] uppercase text-[--text-dim] border border-[--ink-border] px-1.5 py-0.5">
          {article.country_code.toUpperCase()}
        </span>
      )}
      <span className="font-[family-name:var(--font-dm-mono)] text-[0.58rem] text-[--text-dim] ml-auto">{time}</span>
    </div>
  )

  const Tags = () => tags.length > 0 ? (
    <div className="flex gap-1.5 ml-auto">
      {tags.map(tag => (
        <span key={tag} className="font-[family-name:var(--font-dm-mono)] text-[0.52rem] tracking-[0.08em] uppercase text-[--text-dim] border border-[--ink-border] px-2 py-1">
          {tag}
        </span>
      ))}
    </div>
  ) : null

  if (hero) {
    return (
      <Link href={`/${lang}/article/${article.meta_slug}`} className="block bg-[--ink-card] border-b border-[--ink-border] p-7 hover:bg-[--ink-hover] transition-colors group">
        <Meta />
        <h2 className="font-[family-name:var(--font-playfair)] text-[1.55rem] font-normal leading-[1.22] tracking-tight text-[--text] mb-2.5 group-hover:text-white transition-colors">
          {article.headline}
        </h2>
        {article.body && (
          <p className="text-[0.82rem] leading-[1.65] text-[--text-dim] mb-3.5 line-clamp-3">
            {article.body.slice(0, 280)}
          </p>
        )}
        <div className="flex items-center gap-2.5">
          <span className="font-[family-name:var(--font-dm-mono)] text-[0.54rem] tracking-[0.12em] uppercase text-[--text-dim]">{t.feed.readMore}</span>
          <Tags />
        </div>
      </Link>
    )
  }

  return (
    <Link
      href={`/${lang}/article/${article.meta_slug}`}
      className="grid border-b border-[--ink-border] hover:bg-[--ink-hover] transition-colors group relative"
      style={{ gridTemplateColumns: '64px 1fr' }}
    >
      <div className="absolute left-0 top-0 w-[2px] h-0 bg-[--gold] group-hover:h-full transition-all duration-200" />
      <div className="flex flex-col items-center justify-start gap-1.5 py-[18px] border-r border-[--ink-border]">
        <span className="font-[family-name:var(--font-dm-mono)] text-[0.58rem] text-[--text-dim]">{time}</span>
        <span className="w-1 h-1 rounded-full bg-[--ink-border] group-hover:bg-[--gold] transition-colors" />
      </div>
      <div className="p-[18px]">
        <Meta />
        <h3 className="font-[family-name:var(--font-playfair)] text-[1rem] font-normal leading-[1.35] tracking-[-0.01em] text-[--text] mb-1.5 group-hover:text-white transition-colors">
          {article.headline}
        </h3>
        {article.body && (
          <p className="text-[0.78rem] leading-[1.62] text-[--text-dim] line-clamp-2 mb-2.5">
            {article.body.slice(0, 160)}
          </p>
        )}
        <div className="flex items-center gap-2">
          <span className="font-[family-name:var(--font-dm-mono)] text-[0.54rem] tracking-[0.12em] uppercase text-[--text-dim]">{t.feed.readMore}</span>
          <Tags />
        </div>
      </div>
    </Link>
  )
}
"""

# ─── src/components/Sidebar.tsx ─────────────────────────────────────────────
files["src/components/Sidebar.tsx"] = """\
import Link from 'next/link'
import { type Lang, useTranslations } from '@/lib/i18n'
import { supabase } from '@/lib/supabase'

async function getTopMovers(lang: string) {
  const { data } = await supabase
    .from('articles')
    .select('headline, meta_slug, stocks(symbol, name), alerts(direction, change_pct)')
    .eq('lang_code', lang)
    .eq('published', true)
    .order('published_at', { ascending: false })
    .limit(5)
  return data ?? []
}

export default async function Sidebar({ lang }: { lang: Lang }) {
  const t = useTranslations(lang)
  const movers = await getTopMovers(lang)

  return (
    <aside className="hidden lg:block w-[280px] shrink-0 pl-7 pt-6">
      <div className="mb-7 pb-7 border-b border-[--ink-border]">
        <div className="font-[family-name:var(--font-dm-mono)] text-[0.52rem] tracking-[0.18em] uppercase text-[--gold] mb-3.5">
          {t.sidebar.movers}
        </div>
        <div className="flex flex-col">
          {movers.map((item: any) => {
            const up = item.alerts?.direction === 'up'
            return (
              <Link
                key={item.meta_slug}
                href={`/${lang}/article/${item.meta_slug}`}
                className="flex items-center gap-2.5 py-2 border-b border-[--ink-border] last:border-0 hover:opacity-80 transition-opacity"
              >
                <span className="font-[family-name:var(--font-dm-mono)] text-[0.62rem] font-medium text-[--text] w-14 shrink-0">{item.stocks?.symbol}</span>
                <span className="text-[0.7rem] text-[--text-dim] flex-1 truncate">{item.stocks?.name}</span>
                <span className={`font-[family-name:var(--font-dm-mono)] text-[0.65rem] font-medium shrink-0 ${up ? 'text-[--up]' : 'text-[--down]'}`}>
                  {up ? '+' : ''}{Number(item.alerts?.change_pct ?? 0).toFixed(1)}%
                </span>
              </Link>
            )
          })}
        </div>
      </div>

      <div className="mb-7 pb-7 border-b border-[--ink-border]">
        <div className="font-[family-name:var(--font-dm-mono)] text-[0.52rem] tracking-[0.18em] uppercase text-[--gold] mb-3.5">
          {t.sidebar.indices}
        </div>
        <Link href={`/${lang}/markets`} className="font-[family-name:var(--font-dm-mono)] text-[0.54rem] tracking-[0.12em] uppercase text-[--text-dim] hover:text-[--gold] transition-colors">
          {t.sidebar.allMarkets}
        </Link>
      </div>

      <div className="mb-7">
        <div className="font-[family-name:var(--font-dm-mono)] text-[0.52rem] tracking-[0.18em] uppercase text-[--gold] mb-3.5">
          {t.sidebar.topics}
        </div>
        <div className="flex flex-wrap gap-1.5">
          {(['earnings','analysts','ai','banks','energy','evs','macro'] as const).map(key => (
            <Link
              key={key}
              href={`/${lang}/topics?tag=${key}`}
              className="font-[family-name:var(--font-dm-mono)] text-[0.52rem] tracking-[0.08em] uppercase text-[--text-dim] border border-[--ink-border] px-2 py-1 hover:text-[--gold] hover:border-[--gold-border] transition-all"
            >
              {t.topics[key]}
            </Link>
          ))}
        </div>
      </div>
    </aside>
  )
}
"""

# ─── src/app/[lang]/article/[slug]/page.tsx ─────────────────────────────────
files["src/app/[lang]/article/[slug]/page.tsx"] = """\
import { notFound } from 'next/navigation'
import { supabase } from '@/lib/supabase'
import { useTranslations, type Lang } from '@/lib/i18n'
import { parseTags } from '@/lib/types'
import Link from 'next/link'
import type { Metadata } from 'next'

export const revalidate = 3600

async function getArticle(slug: string, lang: string) {
  const { data, error } = await supabase
    .from('articles')
    .select('*, stocks(symbol, name, sector, cap_tier, country_code), alerts(direction, change_pct, price_at_alert, previous_close, triggered_at)')
    .eq('meta_slug', slug)
    .eq('lang_code', lang)
    .eq('published', true)
    .single()
  if (error || !data) return null
  return data
}

async function getRelated(stockId: string, lang: string, excludeSlug: string) {
  const { data } = await supabase
    .from('articles')
    .select('headline, meta_slug, stocks(symbol), alerts(direction, change_pct)')
    .eq('lang_code', lang)
    .eq('stock_id', stockId)
    .eq('published', true)
    .neq('meta_slug', excludeSlug)
    .order('published_at', { ascending: false })
    .limit(3)
  return data ?? []
}

export async function generateMetadata({ params }: { params: Promise<{ lang: string; slug: string }> }): Promise<Metadata> {
  const { lang, slug } = await params
  const article = await getArticle(slug, lang)
  if (!article) return {}
  return { title: article.meta_title || article.headline, description: article.meta_description || '' }
}

export default async function ArticlePage({ params }: { params: Promise<{ lang: string; slug: string }> }) {
  const { lang, slug } = await params
  const t = useTranslations(lang as Lang)
  const article = await getArticle(slug, lang)
  if (!article) notFound()

  const stock = (article as any).stocks
  const alert = (article as any).alerts
  const tags = parseTags(article.tags)
  const related = await getRelated(article.stock_id, lang, slug)
  const up = alert?.direction === 'up'

  const publishedDate = new Date(article.published_at).toLocaleDateString(
    lang === 'it' ? 'it-IT' : 'en-GB',
    { day: 'numeric', month: 'long', year: 'numeric' }
  )
  const publishedTime = new Date(article.published_at).toLocaleTimeString(
    lang === 'it' ? 'it-IT' : 'en-GB',
    { hour: '2-digit', minute: '2-digit' }
  )

  return (
    <div className="max-w-[1240px] mx-auto px-[--pad]">
      <div className="flex items-center gap-3.5 pt-5">
        <Link href={`/${lang}`} className="font-[family-name:var(--font-dm-mono)] text-[0.54rem] tracking-[0.12em] uppercase text-[--text-dim] hover:text-[--gold] transition-colors">
          {t.article.back}
        </Link>
        <div className="flex-1 h-px bg-[--ink-border]" />
      </div>

      <div className="grid border-t border-[--ink-border] mt-0" style={{ gridTemplateColumns: '1fr 280px' }}>
        <article className="py-8 pr-11 border-r border-[--ink-border]">
          <div className="font-[family-name:var(--font-dm-mono)] text-[0.54rem] tracking-[0.18em] uppercase text-[--gold] mb-3">
            {stock?.country_code?.toUpperCase()} \u00b7 {stock?.sector} \u00b7 {publishedDate}, {publishedTime}
          </div>
          <h1 className="font-[family-name:var(--font-playfair)] text-[1.85rem] font-normal leading-[1.22] tracking-tight text-[--text] mb-3.5">
            {article.headline}
          </h1>
          <div className="flex items-center gap-2.5 flex-wrap text-[0.7rem] text-[--text-dim] pb-5 mb-5 border-b border-[--ink-border]">
            <span>{t.article.byline}</span>
            <span className="font-[family-name:var(--font-dm-mono)] text-[0.54rem] text-[--up] border border-[#2d4a34] px-[7px] py-[2px]">
              {t.article.factChecked}
            </span>
            <span>{publishedTime}</span>
          </div>

          <div className="flex gap-1.5 mb-5 pb-5 border-b border-[--ink-border]">
            <Link href={`/en/article/${slug}`} className={`flex items-center gap-1 px-2.5 py-1 border font-[family-name:var(--font-dm-mono)] text-[0.58rem] transition-all ${lang === 'en' ? 'text-[--text] border-[#3a3830] bg-[--ink-raised]' : 'text-[--text-dim] border-[--ink-border] hover:text-[--gold] hover:border-[--gold-border]'}`}>
              \U0001f1ec\U0001f1e7 English
            </Link>
            <Link href={`/it/article/${slug}`} className={`flex items-center gap-1 px-2.5 py-1 border font-[family-name:var(--font-dm-mono)] text-[0.58rem] transition-all ${lang === 'it' ? 'text-[--text] border-[#3a3830] bg-[--ink-raised]' : 'text-[--text-dim] border-[--ink-border] hover:text-[--gold] hover:border-[--gold-border]'}`}>
              \U0001f1ee\U0001f1f9 Italiano
            </Link>
          </div>

          <div className="space-y-4 mb-7">
            {article.body?.split('\\n\\n').filter(Boolean).map((para: string, i: number) => (
              <p key={i} className={`leading-[1.82] text-[--text] ${i === 0 ? 'text-[0.95rem]' : 'text-[0.88rem]'}`}>{para}</p>
            ))}
          </div>

          {article.explainer_body && (
            <>
              <div className="flex items-center gap-3 my-7">
                <span className="font-[family-name:var(--font-dm-mono)] text-[0.54rem] tracking-[0.16em] uppercase text-[--gold] whitespace-nowrap">
                  {t.article.whatItMeans}
                </span>
                <div className="flex-1 h-px bg-[--ink-border]" />
              </div>
              <div className="space-y-4">
                {article.explainer_body.split('\\n\\n').filter(Boolean).map((para: string, i: number) => (
                  <p key={i} className="text-[0.88rem] leading-[1.82] text-[--text]">{para}</p>
                ))}
              </div>
            </>
          )}

          {tags.length > 0 && (
            <div className="mt-8 pt-6 border-t border-[--ink-border]">
              <div className="font-[family-name:var(--font-dm-mono)] text-[0.52rem] tracking-[0.16em] uppercase text-[--text-dim] mb-2.5">{t.article.tags}</div>
              <div className="flex flex-wrap gap-1.5">
                {tags.map((tag: string) => (
                  <Link key={tag} href={`/${lang}/topics?tag=${tag}`} className="font-[family-name:var(--font-dm-mono)] text-[0.52rem] tracking-[0.08em] uppercase text-[--text-dim] border border-[--ink-border] px-2 py-1 hover:text-[--gold] hover:border-[--gold-border] transition-all">
                    {tag}
                  </Link>
                ))}
              </div>
            </div>
          )}
        </article>

        <aside className="pl-7 pt-8">
          {stock && alert && (
            <div className="mb-6 pb-6 border-b border-[--ink-border]">
              <div className="font-[family-name:var(--font-dm-mono)] text-[0.52rem] tracking-[0.16em] uppercase text-[--text-dim] mb-3">
                {stock.symbol} \u00b7 {stock.name}
              </div>
              <div className="font-[family-name:var(--font-dm-mono)] text-[1.8rem] font-medium text-[--text] leading-none mb-1.5">
                {alert.price_at_alert ? `${stock.country_code === 'us' ? '$' : '\u20ac'}${Number(alert.price_at_alert).toFixed(2)}` : '\u2014'}
              </div>
              <div className={`flex items-center gap-2 font-[family-name:var(--font-dm-mono)] text-[0.75rem] mb-4 ${up ? 'text-[--up]' : 'text-[--down]'}`}>
                <span>{up ? '+' : ''}{Number(alert.change_pct).toFixed(1)}%</span>
              </div>
              {([
                [t.article.previousClose, alert.previous_close ? `${stock.country_code === 'us' ? '$' : '\u20ac'}${Number(alert.previous_close).toFixed(2)}` : '\u2014'],
                [t.article.capTier, stock.cap_tier ? (stock.cap_tier === 'large' ? t.article.large : stock.cap_tier === 'mid' ? t.article.mid : t.article.small) : '\u2014'],
                [t.article.moveThreshold, stock.cap_tier === 'large' ? '\u00b14.0%' : stock.cap_tier === 'mid' ? '\u00b18.0%' : '\u00b110.0%'],
              ] as [string, string][]).map(([label, value]) => (
                <div key={label} className="flex justify-between py-1.5 border-b border-[--ink-border] last:border-0 text-[0.7rem]">
                  <span className="text-[--text-dim]">{label}</span>
                  <span className="font-[family-name:var(--font-dm-mono)] text-[--text]">{value}</span>
                </div>
              ))}
            </div>
          )}

          {related.length > 0 && (
            <div className="mb-6 pb-6 border-b border-[--ink-border]">
              <div className="font-[family-name:var(--font-dm-mono)] text-[0.52rem] tracking-[0.16em] uppercase text-[--text-dim] mb-3">{t.article.related}</div>
              <div className="flex flex-col gap-3.5">
                {related.map((r: any) => (
                  <Link key={r.meta_slug} href={`/${lang}/article/${r.meta_slug}`} className="group">
                    <div className="flex items-center gap-2 mb-1">
                      <span className="font-[family-name:var(--font-dm-mono)] text-[0.56rem] text-[--text] bg-[--ink-border] px-1.5 py-0.5">{r.stocks?.symbol}</span>
                      <span className={`font-[family-name:var(--font-dm-mono)] text-[0.58rem] ${r.alerts?.direction === 'up' ? 'text-[--up]' : 'text-[--down]'}`}>
                        {r.alerts?.direction === 'up' ? '+' : ''}{Number(r.alerts?.change_pct ?? 0).toFixed(1)}%
                      </span>
                    </div>
                    <div className="font-[family-name:var(--font-playfair)] text-[0.8rem] leading-[1.35] text-[--text] group-hover:text-white transition-colors">
                      {r.headline}
                    </div>
                  </Link>
                ))}
              </div>
            </div>
          )}
        </aside>
      </div>
    </div>
  )
}
"""

# ─── src/app/[lang]/markets/page.tsx ────────────────────────────────────────
files["src/app/[lang]/markets/page.tsx"] = """\
import { supabase } from '@/lib/supabase'
import { useTranslations, type Lang } from '@/lib/i18n'
import { COUNTRIES } from '@/lib/countries'
import Link from 'next/link'

export const revalidate = 300

async function getMarketArticles(countryCode: string, lang: string) {
  const { data } = await supabase
    .from('articles')
    .select('id, headline, meta_slug, published_at')
    .eq('country_code', countryCode)
    .eq('lang_code', lang)
    .eq('published', true)
    .order('published_at', { ascending: false })
    .limit(5)
  return data ?? []
}

export default async function MarketsPage({ params }: { params: Promise<{ lang: string }> }) {
  const { lang } = await params
  const t = useTranslations(lang as Lang)
  const active = COUNTRIES.filter(c => c.active)
  const soon   = COUNTRIES.filter(c => !c.active)

  const statsMap: Record<string, any[]> = {}
  await Promise.all(active.map(async c => { statsMap[c.code] = await getMarketArticles(c.code, lang) }))

  return (
    <div className="max-w-[1240px] mx-auto px-[--pad]">
      <div className="py-8 border-b border-[--ink-border]">
        <h1 className="font-[family-name:var(--font-playfair)] text-[clamp(1.5rem,2.5vw,2.2rem)] font-normal tracking-tight text-[--text] mb-1.5">{t.markets.title}</h1>
        <p className="text-[0.82rem] text-[--text-dim] max-w-lg">{t.markets.sub}</p>
      </div>

      <div className="flex items-center gap-3.5 py-6">
        <span className="font-[family-name:var(--font-dm-mono)] text-[0.54rem] tracking-[0.18em] uppercase text-[--gold] whitespace-nowrap">{t.markets.active}</span>
        <div className="flex-1 h-px bg-[--ink-border]" />
      </div>

      <div className="grid gap-px bg-[--ink-border] border border-[--ink-border]" style={{ gridTemplateColumns: 'repeat(auto-fill,minmax(320px,1fr))' }}>
        {active.map(country => {
          const articles = statsMap[country.code] ?? []
          const latest = articles[0]
          return (
            <Link key={country.code} href={`/${lang}/markets/${country.code}`} className="bg-[--ink] p-5 hover:bg-[--ink-hover] transition-colors group">
              <div className="flex justify-between items-start mb-4">
                <div>
                  <div className="text-[1.4rem] mb-1.5 leading-none">{country.flag}</div>
                  <div className="font-[family-name:var(--font-playfair)] text-[1.05rem] text-[--text]">{country.index}</div>
                  <div className="font-[family-name:var(--font-dm-mono)] text-[0.56rem] tracking-[0.1em] uppercase text-[--text-dim] mt-1">{country.name}</div>
                </div>
                <span className="font-[family-name:var(--font-dm-mono)] text-[0.52rem] tracking-[0.1em] uppercase text-[--up] border border-[#2d4a34] px-2 py-1">{t.markets.status.open}</span>
              </div>
              <div className="border-t border-[--ink-border] pt-3.5 mb-3.5">
                <div className="font-[family-name:var(--font-dm-mono)] text-[0.88rem] font-medium text-[--text]">{articles.length}</div>
                <div className="font-[family-name:var(--font-dm-mono)] text-[0.5rem] tracking-[0.1em] uppercase text-[--text-dim] mt-1">{t.markets.stat.stories}</div>
              </div>
              {latest && (
                <div className="text-[0.72rem] text-[--text-dim] border-t border-[--ink-border] pt-3 truncate">
                  {lang === 'it' ? 'Ultimo:' : 'Latest:'} {latest.headline}
                </div>
              )}
            </Link>
          )
        })}
      </div>

      <div className="flex items-center gap-3.5 py-6 mt-4">
        <span className="font-[family-name:var(--font-dm-mono)] text-[0.54rem] tracking-[0.18em] uppercase text-[--gold] whitespace-nowrap">{t.markets.soon}</span>
        <div className="flex-1 h-px bg-[--ink-border]" />
      </div>

      <div className="grid gap-px bg-[--ink-border] border border-[--ink-border] mb-12 opacity-40" style={{ gridTemplateColumns: 'repeat(auto-fill,minmax(200px,1fr))' }}>
        {soon.map(country => (
          <div key={country.code} className="bg-[--ink] p-5">
            <div className="text-[1.3rem] mb-1.5 leading-none">{country.flag}</div>
            <div className="font-[family-name:var(--font-playfair)] text-[1rem] text-[--text]">{country.index}</div>
            <div className="font-[family-name:var(--font-dm-mono)] text-[0.56rem] tracking-[0.1em] uppercase text-[--text-dim] mt-1">{country.name}</div>
            <div className="font-[family-name:var(--font-dm-mono)] text-[0.52rem] tracking-[0.1em] uppercase text-[--text-dim] border border-[--ink-border] px-2 py-1 inline-block mt-3">{t.markets.status.soon}</div>
          </div>
        ))}
      </div>
    </div>
  )
}
"""

# ─── src/app/[lang]/markets/[country]/page.tsx ──────────────────────────────
files["src/app/[lang]/markets/[country]/page.tsx"] = """\
import { notFound } from 'next/navigation'
import { supabase } from '@/lib/supabase'
import { useTranslations, type Lang } from '@/lib/i18n'
import { getCountry } from '@/lib/countries'
import FeedItem from '@/components/FeedItem'

export const revalidate = 60

async function getArticles(countryCode: string, lang: string) {
  const { data } = await supabase
    .from('articles')
    .select('*, stocks(symbol, name, sector, cap_tier, country_code), alerts(direction, change_pct, price_at_alert, previous_close, triggered_at)')
    .eq('country_code', countryCode)
    .eq('lang_code', lang)
    .eq('published', true)
    .order('published_at', { ascending: false })
    .limit(30)
  return data ?? []
}

export default async function MarketDetailPage({ params }: { params: Promise<{ lang: string; country: string }> }) {
  const { lang, country } = await params
  const t = useTranslations(lang as Lang)
  const countryConfig = getCountry(country)
  if (!countryConfig || !countryConfig.active) notFound()

  const articles = await getArticles(country, lang)

  return (
    <div className="max-w-[1240px] mx-auto px-[--pad]">
      <div className="py-8 border-b border-[--ink-border]">
        <div className="font-[family-name:var(--font-dm-mono)] text-[0.54rem] tracking-[0.16em] uppercase text-[--gold] mb-2">{countryConfig.flag} {countryConfig.name}</div>
        <h1 className="font-[family-name:var(--font-playfair)] text-[clamp(1.5rem,2.5vw,2.2rem)] font-normal tracking-tight text-[--text]">{countryConfig.index}</h1>
      </div>
      <div className="flex items-center gap-3.5 py-6">
        <span className="font-[family-name:var(--font-dm-mono)] text-[0.54rem] tracking-[0.18em] uppercase text-[--gold] whitespace-nowrap">{t.markets.latest}</span>
        <div className="flex-1 h-px bg-[--ink-border]" />
      </div>
      <div className="border-t border-[--ink-border]">
        {articles.map((article, i) => (
          <FeedItem key={article.id} article={article} lang={lang as Lang} hero={i === 0} />
        ))}
        {articles.length === 0 && (
          <div className="py-10 font-[family-name:var(--font-dm-mono)] text-[0.62rem] text-[--text-dim]">
            {lang === 'it' ? 'Nessun articolo disponibile.' : 'No articles available yet.'}
          </div>
        )}
      </div>
    </div>
  )
}
"""

# ─── src/app/[lang]/topics/page.tsx ─────────────────────────────────────────
files["src/app/[lang]/topics/page.tsx"] = """\
import { supabase } from '@/lib/supabase'
import { useTranslations, type Lang } from '@/lib/i18n'
import FeedItem from '@/components/FeedItem'
import TopicsClient from '@/components/TopicsClient'

export const revalidate = 120

async function getArticles(lang: string, tag?: string) {
  let query = supabase
    .from('articles')
    .select('*, stocks(symbol, name, sector, cap_tier, country_code), alerts(direction, change_pct, price_at_alert, previous_close, triggered_at)')
    .eq('lang_code', lang)
    .eq('published', true)
    .order('published_at', { ascending: false })
    .limit(20)

  if (tag) query = query.contains('tags', JSON.stringify([tag]))
  const { data } = await query
  return data ?? []
}

export default async function TopicsPage({
  params,
  searchParams,
}: {
  params: Promise<{ lang: string }>
  searchParams: Promise<{ tag?: string }>
}) {
  const { lang } = await params
  const { tag } = await searchParams
  const t = useTranslations(lang as Lang)
  const articles = await getArticles(lang, tag)
  const topicKeys = ['earnings','analysts','ai','banks','energy','evs','semiconductors','macro','ma','rates','ipo','fda','trade'] as const

  return (
    <div className="max-w-[1240px] mx-auto px-[--pad]">
      <div className="py-8 border-b border-[--ink-border]">
        <h1 className="font-[family-name:var(--font-playfair)] text-[clamp(1.5rem,2.5vw,2.2rem)] font-normal tracking-tight text-[--text] mb-4">{t.topics.title}</h1>
        <TopicsClient lang={lang as Lang} activeTag={tag} topics={topicKeys.map(k => ({ slug: k, label: t.topics[k] }))} />
      </div>
      <div className="border-t border-[--ink-border] mt-2">
        {articles.map((article, i) => (
          <FeedItem key={article.id} article={article} lang={lang as Lang} hero={i === 0} />
        ))}
        {articles.length === 0 && (
          <div className="py-10 font-[family-name:var(--font-dm-mono)] text-[0.62rem] text-[--text-dim]">{t.archive.noResults}</div>
        )}
      </div>
    </div>
  )
}
"""

# ─── src/components/TopicsClient.tsx ────────────────────────────────────────
files["src/components/TopicsClient.tsx"] = """\
'use client'

import { useRouter } from 'next/navigation'
import { type Lang } from '@/lib/i18n'

export default function TopicsClient({
  lang,
  activeTag,
  topics,
}: {
  lang: Lang
  activeTag?: string
  topics: { slug: string; label: string }[]
}) {
  const router = useRouter()
  const select = (slug: string) => {
    router.push(slug === activeTag ? `/${lang}/topics` : `/${lang}/topics?tag=${slug}`)
  }
  return (
    <div className="flex flex-wrap gap-2">
      {topics.map(({ slug, label }) => (
        <button
          key={slug}
          onClick={() => select(slug)}
          className={`font-[family-name:var(--font-dm-mono)] text-[0.6rem] tracking-[0.06em] px-3.5 py-2 border transition-all
            ${activeTag === slug
              ? 'text-[--gold] border-[--gold-border] bg-[rgba(196,162,94,0.06)]'
              : 'text-[--text-dim] border-[--ink-border] hover:text-[--gold] hover:border-[--gold-border]'}`}
        >
          {label}
        </button>
      ))}
    </div>
  )
}
"""

# ─── src/app/[lang]/search/page.tsx ─────────────────────────────────────────
files["src/app/[lang]/search/page.tsx"] = """\
import { supabase } from '@/lib/supabase'
import { useTranslations, type Lang } from '@/lib/i18n'
import FeedItem from '@/components/FeedItem'
import SearchClient from '@/components/SearchClient'

async function searchArticles(query: string, lang: string) {
  if (!query || query.length < 2) return []
  const { data } = await supabase
    .from('articles')
    .select('*, stocks(symbol, name, sector, cap_tier, country_code), alerts(direction, change_pct, price_at_alert, previous_close, triggered_at)')
    .eq('lang_code', lang)
    .eq('published', true)
    .ilike('headline', `%${query}%`)
    .order('published_at', { ascending: false })
    .limit(20)
  return data ?? []
}

export default async function SearchPage({
  params,
  searchParams,
}: {
  params: Promise<{ lang: string }>
  searchParams: Promise<{ q?: string }>
}) {
  const { lang } = await params
  const { q } = await searchParams
  const t = useTranslations(lang as Lang)
  const articles = q ? await searchArticles(q, lang) : []

  return (
    <div className="max-w-[1240px] mx-auto px-[--pad]">
      <div className="py-8 border-b border-[--ink-border]">
        <h1 className="font-[family-name:var(--font-playfair)] text-[clamp(1.5rem,2.5vw,2.2rem)] font-normal tracking-tight text-[--text] mb-5">{t.search.title}</h1>
        <SearchClient lang={lang as Lang} initialQuery={q} />
        <p className="font-[family-name:var(--font-dm-mono)] text-[0.54rem] tracking-[0.1em] text-[--text-dim] mt-3">{t.search.hint}</p>
      </div>
      {q && (
        <div className="border-t border-[--ink-border] mt-2">
          {articles.length === 0
            ? <div className="py-10 font-[family-name:var(--font-dm-mono)] text-[0.62rem] text-[--text-dim]">{t.archive.noResults}</div>
            : articles.map((article, i) => <FeedItem key={article.id} article={article} lang={lang as Lang} hero={i === 0} />)
          }
        </div>
      )}
    </div>
  )
}
"""

# ─── src/components/SearchClient.tsx ────────────────────────────────────────
files["src/components/SearchClient.tsx"] = """\
'use client'

import { useRouter } from 'next/navigation'
import { useState } from 'react'
import { type Lang, useTranslations } from '@/lib/i18n'

export default function SearchClient({ lang, initialQuery }: { lang: Lang; initialQuery?: string }) {
  const t = useTranslations(lang)
  const router = useRouter()
  const [q, setQ] = useState(initialQuery ?? '')

  const submit = () => {
    if (q.trim()) router.push(`/${lang}/search?q=${encodeURIComponent(q.trim())}`)
  }

  return (
    <div className="flex max-w-[560px] border border-[--ink-border] bg-[--ink-raised]">
      <input
        type="text"
        value={q}
        onChange={e => setQ(e.target.value)}
        onKeyDown={e => e.key === 'Enter' && submit()}
        placeholder={t.search.placeholder}
        className="flex-1 bg-transparent border-none px-3 py-3 text-[0.88rem] text-[--text] placeholder:text-[--text-dim] outline-none"
      />
      <button
        onClick={submit}
        className="border-l border-[--ink-border] px-3 font-[family-name:var(--font-dm-mono)] text-[0.56rem] tracking-[0.1em] uppercase text-[--text-dim] hover:text-[--gold] transition-colors"
      >
        {t.search.go}
      </button>
    </div>
  )
}
"""

# ─── src/app/[lang]/archive/page.tsx ────────────────────────────────────────
files["src/app/[lang]/archive/page.tsx"] = """\
import { supabase } from '@/lib/supabase'
import { useTranslations, type Lang } from '@/lib/i18n'
import ArchiveClient from '@/components/ArchiveClient'

export const revalidate = 300

async function getArchiveArticles(lang: string) {
  const { data } = await supabase
    .from('articles')
    .select('id, headline, meta_slug, published_at, country_code, tags, stocks(symbol, name), alerts(direction, change_pct)')
    .eq('lang_code', lang)
    .eq('published', true)
    .order('published_at', { ascending: false })
    .limit(200)
  return data ?? []
}

export default async function ArchivePage({ params }: { params: Promise<{ lang: string }> }) {
  const { lang } = await params
  const t = useTranslations(lang as Lang)
  const articles = await getArchiveArticles(lang)

  return (
    <div className="max-w-[1240px] mx-auto px-[--pad]">
      <div className="py-8 border-b border-[--ink-border]">
        <h1 className="font-[family-name:var(--font-playfair)] text-[clamp(1.5rem,2.5vw,2.2rem)] font-normal tracking-tight text-[--text] mb-1.5">{t.archive.title}</h1>
        <p className="text-[0.82rem] text-[--text-dim]">{t.archive.sub}</p>
      </div>
      <ArchiveClient articles={articles} lang={lang as Lang} t={t} />
    </div>
  )
}
"""

# ─── src/components/ArchiveClient.tsx ───────────────────────────────────────
files["src/components/ArchiveClient.tsx"] = """\
'use client'

import Link from 'next/link'
import { useState, useMemo } from 'react'
import { parseTags } from '@/lib/types'
import type { Lang } from '@/lib/i18n'

type ArchiveArticle = {
  id: string
  headline: string
  meta_slug: string
  published_at: string
  country_code: string
  tags: string | string[]
  stocks?: { symbol: string; name: string } | null
  alerts?: { direction: string; change_pct: number } | null
}

const TOPIC_SLUGS = ['earnings','analysts','ai','banks','energy','evs','semiconductors','macro','ma','rates','ipo','fda','trade']

export default function ArchiveClient({ articles, lang, t }: { articles: ArchiveArticle[]; lang: Lang; t: any }) {
  const [fMarket, setFMarket] = useState('all')
  const [fDir,    setFDir]    = useState('all')
  const [fTopic,  setFTopic]  = useState('all')
  const [drawer,  setDrawer]  = useState(false)

  const filtered = useMemo(() => articles.filter(a => {
    if (fMarket !== 'all' && a.country_code !== fMarket) return false
    if (fDir    !== 'all' && a.alerts?.direction !== fDir) return false
    if (fTopic  !== 'all' && !parseTags(a.tags).includes(fTopic)) return false
    return true
  }), [articles, fMarket, fDir, fTopic])

  const grouped = useMemo(() => {
    const months: Record<string, Record<string, ArchiveArticle[]>> = {}
    for (const a of filtered) {
      const d = new Date(a.published_at)
      const month = d.toLocaleDateString(lang === 'it' ? 'it-IT' : 'en-GB', { month: 'long', year: 'numeric' })
      const day   = d.toLocaleDateString(lang === 'it' ? 'it-IT' : 'en-GB', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' })
      if (!months[month]) months[month] = {}
      if (!months[month][day]) months[month][day] = []
      months[month][day].push(a)
    }
    return months
  }, [filtered, lang])

  const activeCount = [fMarket, fDir, fTopic].filter(v => v !== 'all').length

  const Pill = ({ val, active, onClick, label }: { val: string; active: boolean; onClick: () => void; label: string }) => (
    <button
      onClick={onClick}
      className={`font-[family-name:var(--font-dm-mono)] text-[0.56rem] tracking-[0.06em] px-2.5 py-[5px] border whitespace-nowrap transition-all
        ${active ? 'text-[--gold] border-[--gold-border] bg-[rgba(196,162,94,0.06)]' : 'text-[--text-dim] border-[--ink-border] hover:text-[--gold] hover:border-[--gold-border]'}`}
    >
      {label}
    </button>
  )

  return (
    <>
      {/* Desktop filter bar */}
      <div className="hidden lg:flex items-stretch border-b border-[--ink-border] bg-[--ink-raised] overflow-x-auto">
        {[
          { label: t.archive.filter.market, key: 'market', val: fMarket, set: setFMarket, opts: [['all',t.archive.filter.all],['us','S&P 500'],['it','FTSE MIB']] },
          { label: t.archive.filter.direction, key: 'dir', val: fDir, set: setFDir, opts: [['all',t.archive.filter.all],['up',t.archive.filter.gainers],['down',t.archive.filter.losers]] },
        ].map(group => (
          <div key={group.key} className="flex items-center gap-2 px-4 py-2.5 border-r border-[--ink-border] shrink-0">
            <span className="font-[family-name:var(--font-dm-mono)] text-[0.52rem] tracking-[0.14em] uppercase text-[--text-dim] whitespace-nowrap mr-1">{group.label}</span>
            {group.opts.map(([v, l]) => <Pill key={v} val={v} active={group.val === v} onClick={() => group.set(v)} label={l} />)}
          </div>
        ))}
        <div className="flex items-center gap-2 px-4 py-2.5 overflow-x-auto">
          <span className="font-[family-name:var(--font-dm-mono)] text-[0.52rem] tracking-[0.14em] uppercase text-[--text-dim] whitespace-nowrap mr-1">{t.archive.filter.topic}</span>
          <Pill val="all" active={fTopic==='all'} onClick={() => setFTopic('all')} label={t.archive.filter.all} />
          {TOPIC_SLUGS.map(s => <Pill key={s} val={s} active={fTopic===s} onClick={() => setFTopic(s)} label={t.topics[s] ?? s} />)}
        </div>
      </div>

      {/* Mobile filter button */}
      <button
        className={`lg:hidden w-full flex items-center justify-between px-[--pad] py-3 border-b border-[--ink-border] bg-[--ink-raised] font-[family-name:var(--font-dm-mono)] text-[0.6rem] tracking-[0.1em] uppercase transition-colors ${activeCount > 0 ? 'text-[--gold]' : 'text-[--text-dim]'}`}
        onClick={() => setDrawer(o => !o)}
      >
        <span>{activeCount > 0 ? `${t.archive.filters} (${activeCount})` : t.archive.filters}</span>
        <span className={`transition-transform ${drawer ? 'rotate-180' : ''}`}>\u25bc</span>
      </button>

      {drawer && (
        <div className="lg:hidden border-b border-[--ink-border] bg-[--ink-raised] px-[--pad] py-4 space-y-4">
          {[
            { label: t.archive.filter.market, val: fMarket, set: setFMarket, opts: [['all',t.archive.filter.all],['us','S&P 500'],['it','FTSE MIB']] as [string,string][] },
            { label: t.archive.filter.direction, val: fDir, set: setFDir, opts: [['all',t.archive.filter.all],['up',t.archive.filter.gainers],['down',t.archive.filter.losers]] as [string,string][] },
          ].map(group => (
            <div key={group.label}>
              <div className="font-[family-name:var(--font-dm-mono)] text-[0.52rem] tracking-[0.14em] uppercase text-[--gold] mb-2">{group.label}</div>
              <div className="flex gap-1.5 flex-wrap">
                {group.opts.map(([v,l]) => <Pill key={v} val={v} active={group.val===v} onClick={() => group.set(v)} label={l} />)}
              </div>
            </div>
          ))}
          <div>
            <div className="font-[family-name:var(--font-dm-mono)] text-[0.52rem] tracking-[0.14em] uppercase text-[--gold] mb-2">{t.archive.filter.topic}</div>
            <div className="flex gap-1.5 flex-wrap">
              <Pill val="all" active={fTopic==='all'} onClick={() => setFTopic('all')} label={t.archive.filter.all} />
              {TOPIC_SLUGS.map(s => <Pill key={s} val={s} active={fTopic===s} onClick={() => setFTopic(s)} label={t.topics[s] ?? s} />)}
            </div>
          </div>
          <button onClick={() => setDrawer(false)} className="w-full py-2.5 border border-[--ink-border] font-[family-name:var(--font-dm-mono)] text-[0.6rem] tracking-[0.12em] uppercase text-[--text-dim] hover:text-[--text] transition-all">
            {t.archive.filter.done}
          </button>
        </div>
      )}

      {filtered.length === 0 && (
        <div className="py-12 text-center font-[family-name:var(--font-dm-mono)] text-[0.62rem] text-[--text-dim]">{t.archive.noResults}</div>
      )}

      {Object.entries(grouped).map(([month, days]) => (
        <div key={month} className="mt-6">
          <div className="flex items-center gap-3.5 mb-0">
            <span className="font-[family-name:var(--font-dm-mono)] text-[0.54rem] tracking-[0.18em] uppercase text-[--gold] whitespace-nowrap">{month}</span>
            <div className="flex-1 h-px bg-[--ink-border]" />
          </div>
          {Object.entries(days).map(([day, dayArticles]) => (
            <div key={day} className="grid border-b border-[--ink-border] hover:bg-[--ink-hover] transition-colors" style={{ gridTemplateColumns: '140px 1fr auto' }}>
              <div className="py-4 pr-5 border-r border-[--ink-border]">
                <div className="font-[family-name:var(--font-dm-mono)] text-[0.56rem] tracking-[0.12em] uppercase text-[--text-dim]">
                  {new Date(dayArticles[0].published_at).toLocaleDateString(lang === 'it' ? 'it-IT' : 'en-GB', { weekday: 'long' })}
                </div>
                <div className="font-[family-name:var(--font-playfair)] text-[1.5rem] font-normal text-[--text] leading-none mt-1">
                  {new Date(dayArticles[0].published_at).getDate()}
                </div>
              </div>
              <div className="py-4 px-5 flex flex-col gap-2">
                {dayArticles.map(a => {
                  const up = a.alerts?.direction === 'up'
                  return (
                    <Link key={a.id} href={`/${lang}/article/${a.meta_slug}`} className="flex items-baseline gap-2.5 group">
                      {a.stocks?.symbol && (
                        <span className="font-[family-name:var(--font-dm-mono)] text-[0.58rem] text-[--text] bg-[--ink-border] px-1.5 py-0.5 shrink-0">{a.stocks.symbol}</span>
                      )}
                      {a.alerts?.change_pct != null && (
                        <span className={`font-[family-name:var(--font-dm-mono)] text-[0.58rem] shrink-0 ${up ? 'text-[--up]' : 'text-[--down]'}`}>
                          {up ? '+' : ''}{Number(a.alerts.change_pct).toFixed(1)}%
                        </span>
                      )}
                      <span className="text-[0.78rem] text-[--text-dim] group-hover:text-[--text] transition-colors truncate">{a.headline}</span>
                    </Link>
                  )
                })}
              </div>
              <div className="py-4 pl-4 text-right shrink-0">
                <div className="font-[family-name:var(--font-dm-mono)] text-[0.7rem] text-[--text]">{dayArticles.length}</div>
                <div className="font-[family-name:var(--font-dm-mono)] text-[0.5rem] tracking-[0.1em] uppercase text-[--text-dim] mt-0.5">{t.archive.stories}</div>
              </div>
            </div>
          ))}
        </div>
      ))}
    </>
  )
}
"""

# ─── Write all files ─────────────────────────────────────────────────────────
written = 0
for rel_path, content in files.items():
    full_path = os.path.join(BASE, rel_path)
    os.makedirs(os.path.dirname(full_path), exist_ok=True)
    with open(full_path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"  wrote {rel_path}")
    written += 1

print(f"\nDone — {written} files written to {BASE}")
